export const RESUME_DATA = {
  name: "Warda Aslam",
  location: "Islamabad, Pakistan",
  contact: {
    phone: "+92 333 5871172",
    email: "wardaaslam122@gmail.com",
    linkedin: "https://www.linkedin.com/in/warda-aslam-838020338",
    github: "https://github.com/warda-git",
  },
  summary: "Computer Science undergraduate at Air University with a strong focus on Cybersecurity, Software Development, and System Design. Experienced in building secure, database-driven applications and leading university-level technical and cultural initiatives. Passionate about cybersecurity engineering, ethical hacking, and full-stack development.",
  education: [
    {
      degree: "BS Computer Science",
      institution: "Air University, Islamabad",
      period: "2024– Present",
    },
    {
      degree: "FSc (Pre-Medical)",
      institution: "Islamabad College for Girls, F-6/2",
      period: "2021– 2023",
      score: "84.8%",
    },
    {
      degree: "Matriculation (Science)",
      institution: "Islamabad College for Girls, F-6/2",
      period: "2019– 2021",
      score: "93.7%",
    },
  ],
  skills: {
    programming: ["C++", "Python", "C#", "PHP", "Dart", "HTML", "CSS"],
    databases: ["SQL Server", "MySQL"],
    development: ["Full-Stack Web Development", "Android Development (Flutter)"],
    cybersecurity: ["Ethical Hacking (CEH Foundation)", "Network Security Basics"],
    tools: ["XAMPP", "GitHub", "Canva"],
    soft: ["Leadership", "Public Speaking", "Event Management", "Team Coordination"],
  },
  projects: [
    {
      title: "Python Network Sniffer",
      subtitle: "Real-Time Packet Analysis Tool",
      description: "Developed a Python-based network monitoring system using Scapy to capture and analyze TCP, UDP, and ICMP packets in real time. Extracted IP addresses, ports, and protocol-level traffic insights for network analysis and security monitoring.",
      category: "Cybersecurity",
      tags: ["Python", "Scapy", "Networking"],
      link: "https://github.com/warda-git/network-sniffer",
    },
    {
      title: "SwapStack",
      subtitle: "Peer-to-Peer Skill Exchange Platform",
      description: "Designed a web-based platform enabling students to exchange skills using a credit-based system. Implemented user profiling, matching algorithm logic, and secure transaction tracking for skill exchange integrity.",
      category: "Full-Stack",
      tags: ["PHP", "SQL Server", "XAMPP"],
    },
    {
      title: "SpendWise",
      subtitle: "Expense Management Mobile Application",
      description: "Developed an Android application for personal finance tracking with categorized budgeting, expense logging, and an intuitive user interface for improved financial awareness and control.",
      category: "Mobile",
      tags: ["Flutter", "Dart", "Firebase"],
      link: "https://github.com/warda-git/expanse_manager_app",
    },
    {
      title: "Full-Stack Database App",
      subtitle: "PHP & SQL Server System",
      description: "Developed a PHP and SQL Server-based full-stack application using XAMPP. Enabled real-time database operations including data insertion, retrieval, update, and deletion.",
      category: "Database",
      tags: ["PHP", "SQL Server", "XAMPP"],
      link: "https://github.com/warda-git/CS130_DB_Project_Warda_Aslam",
    },
    {
      title: "Secure Notes App",
      subtitle: "Encrypted Mobile Notes",
      description: "Built a Flutter-based secure note-taking application with AES encryption. Implemented encrypted local storage using SharedPreferences and ensured data confidentiality through runtime encryption and decryption.",
      category: "Cybersecurity/Mobile",
      tags: ["Flutter", "AES Encryption", "Security"],
    },
  ],
  leadership: [
    { role: "Director Public Relations", org: "Alphas Society", period: "2025– Present" },
    { role: "Vice President", org: "Cultural & Heritage Society", period: "2025– Present" },
    { role: "Operations Team Member", org: "Google Developers on Campus", period: "2022– 2023" },
    { role: "Campus Ambassador", org: "Pakistan Film Society Islamabad" },
    { role: "Coordination Lead", org: "Air University Convocation & Events" },
    { role: "General Secretary", org: "Student Council" },
  ],
  certifications: [
    "Certified Ethical Hacking (CEH Foundation) – DigiPakistan",
    "Introduction to Cybersecurity – HP LIFE",
    "Android Studio Development – Google",
    "UX Design – Coursera",
    "Social Media Marketing – UniAthena",
    "Master ChatGPT – UniAthena",
  ],
};
